POST http://localhost:3000/register  
Content-Type:application/json

{
    "name":"keshav",
    "username":"keshav12",
    "password":"keshav1234",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login 
Content-Type: application/json 

{
    "username":"keshav12",
    "password":"keshav1234"
}

### 

GET http://localhost:3000/users/

Authorization: bearer 
