POST http://localhost:3000/register  
Content-Type:application/json

{
    "name":"mahi",
    "username":"mahesh12",
    "password":"mahesh1234",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login 
Content-Type: application/json 

{
    "username":"mahesh12",
    "password":"mahesh1234"
}

###
GET http://localhost:3000/users/

Authorization: 




